# Generated by Django 4.2.6 on 2023-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=500)),
                ('short_code', models.CharField(max_length=100)),
                ('date_time_created', models.DateTimeField()),
            ],
        ),
    ]
